#!/usr/bin/env python3
"""Generate the frontend's copy of the requirement-lint rule table.

Run from backend/:  .venv/bin/python gen_quality_rules.py

Writes ``frontend/src/lib/generated/qualityRules.ts`` from
:mod:`app.services.quality_rules` (the rule table and the modal keywords) and
:mod:`app.services.quality` (the default config), so the live editor score and
the server-side score check the same things from the same data. That file is
generated — never hand-edit it — as with ``schemas/*.json``.

A sibling of gen_schemas.py / gen_write_models.py / gen_api_reference.py: those
turn the Pydantic models and the route table into generated artifacts, this one
turns the rule table into the client's data module. They share nothing but the
"regenerate, then gate the diff in CI" discipline.

Exits non-zero with ``--check`` if the committed file is out of date, which is
what CI uses to stop the two from drifting again.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from app.services.quality import DEFAULT_CONFIG
from app.services.quality_rules import PATTERN_RULES, modal_keywords

OUT = Path(__file__).resolve().parent.parent / "frontend" / "src" / "lib" / "generated" / "qualityRules.ts"

HEADER = """\
// AUTO-GENERATED — do not edit.
// Generated by backend/gen_quality_rules.py from the rule table in
// backend/app/services/quality_rules.py and the default config in
// backend/app/services/quality.py. Any edits here are overwritten the next
// time the generator runs, and CI regenerates and diffs this file on every
// push — so a rule change without regenerating fails the build.
//
// Regenerate with: backend/.venv/bin/python backend/gen_quality_rules.py
"""


def rule_table() -> list[dict]:
    """The pattern rules as the client consumes them — data, not code.

    ``config`` is the resolved ``_meta.yaml`` key (``rule.config``), so the
    client's enable/disable and weight lookups use exactly the same keys the
    server's ``_load_config`` produces.
    """
    return [
        {
            "id": r.id,
            "config": r.config,
            "pattern": r.pattern,
            "severity": r.severity,
            "message": r.message,
            "weight": r.weight,
            "enabled": r.enabled,
        }
        for r in PATTERN_RULES
    ]


def render() -> str:
    chunks = [HEADER]

    chunks.append("export type Severity = 'error' | 'warning' | 'info';")
    chunks.append("")
    chunks.append("export interface QualityRule {")
    chunks.append("  id: string;")
    chunks.append("  /** The `_meta.yaml` quality.rules / quality.weights key for this rule. */")
    chunks.append("  config: string;")
    chunks.append("  /** Portable regex source. Compile fresh with `gi` per call — see lib/quality.ts. */")
    chunks.append("  pattern: string;")
    chunks.append("  severity: Severity;")
    chunks.append("  /** Template with a single `{match}` placeholder. */")
    chunks.append("  message: string;")
    chunks.append("  weight: number;")
    chunks.append("  enabled: boolean;")
    chunks.append("}")
    chunks.append("")
    chunks.append(f"export const QUALITY_RULES: QualityRule[] = {json.dumps(rule_table(), ensure_ascii=False, indent=2)};")
    chunks.append("")
    chunks.append("export interface ModalSets {")
    chunks.append("  binding: string[];")
    chunks.append("  advisory: string[];")
    chunks.append("}")
    chunks.append("")
    chunks.append(f"export const MODALS: ModalSets = {json.dumps(modal_keywords(), ensure_ascii=False, indent=2)};")
    chunks.append("")
    chunks.append("export interface QualityDefaults {")
    chunks.append("  min_words: number;")
    chunks.append("  max_words: number;")
    chunks.append("  rules: Record<string, boolean>;")
    chunks.append("  weights: Record<string, number>;")
    chunks.append("}")
    chunks.append("")
    chunks.append(f"export const DEFAULT_CONFIG: QualityDefaults = {json.dumps(DEFAULT_CONFIG, ensure_ascii=False, indent=2)};")
    chunks.append("")

    return "\n".join(chunks)


def main() -> int:
    want = render()
    check = "--check" in sys.argv
    have = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    if check:
        if have != want:
            print(f"out of date: {OUT}\nrun: .venv/bin/python gen_quality_rules.py", file=sys.stderr)
            return 1
        print(f"up to date: {OUT}")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(want, encoding="utf-8")
    print(f"wrote {OUT} ({len(rule_table())} rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
