#!/usr/bin/env python3
"""Generate docs/api.md — the API reference — from the live OpenAPI schema.

Run from backend/:  .venv/bin/python gen_api_reference.py
Output goes to ../docs/api.md

A sibling of gen_schemas.py and gen_write_models.py: those turn the Pydantic
models into JSON Schemas and TypeScript interfaces, this one turns the *live
route table* into Markdown. It is the thing that replaced the hand-written API
tables in README.md, which went stale by construction — see the task note about
finding G-9, where three test counts disagreed three ways.

Routes are enumerated from ``app.openapi()`` (the same table FastAPI serves at
``/openapi.json``) rather than by reading decorators, so a router whose prefix
is set on the ``APIRouter`` itself (e.g. ``system_routes.py`` is
``APIRouter(prefix="/system")``) is not missed. Everything iterated is sorted,
because a CI gate that diffs this file on every push will flap on dict ordering
otherwise.
"""

from __future__ import annotations

from pathlib import Path

from app.main import app

OUT = Path(__file__).resolve().parent.parent / "docs" / "api.md"

_METHODS = ("GET", "POST", "PUT", "PATCH", "DELETE")

# Order the routes appear in the reference. `_section` maps every path to one of
# these names; "Other" exists so an unknown path can never be silently dropped.
_SECTION_ORDER = [
    "Projects",
    "Requirements",
    "Components",
    "Verification",
    "Specifications",
    "Risks",
    "Baselines",
    "System states",
    "Definitions",
    "Analysis cases",
    "Change requests",
    "Comments",
    "Decisions",
    "Review & references",
    "Traces & coverage",
    "Allocation matrix",
    "Analysis & validation",
    "Bulk operations",
    "Publishing & interchange",
    "Git & hooks",
    "Real-time",
    "Test results",
    "Authentication",
    "System (admin)",
    "Health & version",
    "Other",
]

# The first path segment under ``/api/projects/{project_id}/``, mapped to the
# section it belongs in. Routes whose resource is not listed fall into "Other"
# and trip the sanity test, so a new entity kind is never silently uncategorised.
_RESOURCE_SECTION = {
    "workflow": "Projects",
    "requirements": "Requirements",
    "components": "Components",
    "verification": "Verification",
    "specifications": "Specifications",
    "risks": "Risks",
    "risk-matrix": "Risks",
    "risk-bingo": "Risks",
    "baselines": "Baselines",
    "system-states": "System states",
    "definitions": "Definitions",
    "analysis": "Analysis cases",
    "change-requests": "Change requests",
    "comments": "Comments",
    "decisions": "Decisions",
    "review-all": "Review & references",
    "unreviewed": "Review & references",
    "references": "Review & references",
    "scan": "Review & references",
    "traces": "Traces & coverage",
    "trace-model": "Traces & coverage",
    "allocation": "Allocation matrix",
    "allocation-matrix": "Allocation matrix",
    "validate": "Analysis & validation",
    "coverage": "Analysis & validation",
    "metrics": "Analysis & validation",
    "gap-analysis": "Analysis & validation",
    "conflicts": "Analysis & validation",
    "compliance": "Analysis & validation",
    "quality": "Analysis & validation",
    "pugh": "Analysis & validation",
    "backlog": "Analysis & validation",
    "evaluation": "Analysis & validation",
    "history": "Analysis & validation",
    "activity": "Analysis & validation",
    "suspect-links": "Analysis & validation",
    "entities": "Analysis & validation",
    "search": "Analysis & validation",
    "publish": "Publishing & interchange",
    "import": "Publishing & interchange",
    "test-results": "Test results",
    "git": "Git & hooks",
    "hooks": "Git & hooks",
    "events": "Real-time",
    "presence": "Real-time",
}

_BULK_SEGMENTS = {"bulk", "bulk-delete", "bulk-reparent"}

_HEADER = """\
<!-- AUTO-GENERATED — do not edit.
Generated by backend/gen_api_reference.py from the live OpenAPI schema. Any
edit here is overwritten the next time the generator runs, and CI regenerates
and diffs this file on every push — so a route change without regenerating
fails the build.

Regenerate with:  backend/.venv/bin/python backend/gen_api_reference.py
-->

# API Reference

Every HTTP route the app registers, enumerated from the OpenAPI schema
(`GET /openapi.json`) rather than typed by hand. Methods are listed one row per
operation; a path served by several methods therefore appears several times.

"""


def _section(path: str) -> str:
    """The reference section a route belongs in, derived from its path.

    Paths arrive from ``app.openapi()`` with their real parameter names intact
    (``{project_id}``, ``{req_id}``, …). Matching is on those names directly.
    """
    if path in ("/health", "/version"):
        return "Health & version"
    if path == "/api/version":
        return "Health & version"
    if path == "/api/coverage-needs":
        return "Analysis & validation"
    if path.startswith("/api/auth/"):
        return "Authentication"
    if path.startswith("/api/system/"):
        return "System (admin)"
    if path in ("/api/projects", "/api/projects/{project_id}"):
        return "Projects"
    if path.startswith("/api/projects/{project_id}/"):
        rest = path[len("/api/projects/{project_id}/"):]
        segments = rest.split("/")
        if any(seg in _BULK_SEGMENTS for seg in segments[1:]):
            return "Bulk operations"
        return _RESOURCE_SECTION.get(segments[0], "Other")
    return "Other"


def _is_thin_body(request_body: dict | None) -> bool:
    """A request body that carries no schema — the ``data: dict`` bulk routes.

    Those operations accept a free-form JSON object and so contribute almost
    nothing to the OpenAPI schema (the body renders as an empty ``object``).
    They are still real routes; the entries are just thinner than the rest. A
    package to type them properly may land separately.
    """
    if not request_body:
        return False
    content = request_body.get("content", {})
    schema = content.get("application/json", {}).get("schema")
    if not isinstance(schema, dict):
        return False
    if "$ref" in schema:
        return False
    if schema.get("properties"):
        return False
    return schema.get("type") == "object"


def _operations() -> list[tuple[str, str, str, bool]]:
    """(method, path, summary, thin) for every documented HTTP operation.

    Sorted by section order, then path, then method — deterministic, so the CI
    diff gate never flaps on dictionary ordering.
    """
    schema = app.openapi()
    rows: list[tuple[str, str, str, bool]] = []
    for path, methods in schema.get("paths", {}).items():
        for method, operation in methods.items():
            upper = method.upper()
            if upper not in _METHODS:
                continue
            summary = (operation.get("summary") or "").strip()
            thin = _is_thin_body(operation.get("requestBody"))
            rows.append((upper, path, summary, thin))

    def sort_key(row: tuple[str, str, str, bool]) -> tuple:
        method, path, _summary, _thin = row
        return (
            _SECTION_ORDER.index(_section(path)),
            path,
            _METHODS.index(method),
        )

    return sorted(rows, key=sort_key)


def render() -> str:
    """The full contents of docs/api.md, as a string."""
    chunks: list[str] = [_HEADER]

    thin_paths: list[str] = []
    current_section: str | None = None

    for method, path, summary, thin in _operations():
        section = _section(path)
        if section != current_section:
            chunks.append(f"## {section}\n")
            chunks.append("| Method | Endpoint | Description |")
            chunks.append("|--------|----------|-------------|")
            current_section = section
        description = summary if summary else "—"
        chunks.append(f"| {method} | `{path}` | {description} |")
        if thin:
            thin_paths.append(f"`{method} {path}`")

    chunks.append("")
    chunks.append("## Notes\n")
    chunks.append(
        "Routes below accept an untyped JSON body (`data: dict`) and so carry "
        "no request schema in the OpenAPI output. They are real routes with "
        "thinner entries than the rest:"
    )
    if thin_paths:
        chunks.append("")
        for entry in thin_paths:
            chunks.append(f"- {entry}")
    else:
        chunks.append("\n- *(none)*")

    return "\n".join(chunks).rstrip() + "\n"


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render())
    print(f"  wrote {OUT}")


if __name__ == "__main__":
    main()
