#!/usr/bin/env python3
"""Generate the TypeScript read-contract interfaces from the Pydantic models.

Run from backend/:  python gen_read_models.py
Output goes to ../frontend/src/api/generated/readModels.ts

`gen_write_models.py` covers the `*Create` / `*Update` classes. This covers the
*read* models (`Requirement`, `Component`, ...), which were previously
hand-written in `client.ts` and could silently drift from the API. The generated
file is a compile-time reference: `client.ts`'s hand-written types are asserted
assignable to it in `frontend/tests/readModelsDrift.test.ts`, so a field removed
or retyped in Pydantic breaks the frontend typecheck rather than surfacing as a
runtime surprise.
"""

import importlib
import inspect
import pkgutil
from pathlib import Path

from pydantic import BaseModel

import app.models

OUT = Path(__file__).resolve().parent.parent / "frontend" / "src" / "api" / "generated" / "readModels.ts"

HEADER = """\
// AUTO-GENERATED — do not edit.
// Generated by backend/gen_read_models.py from the Pydantic read models in
// backend/app/models/. Any edits here are overwritten the next time the
// generator runs.
//
// This is the read contract. The hand-written interfaces in client.ts are
// asserted assignable to these in frontend/tests/readModelsDrift.test.ts; if a
// field is removed or retyped in Pydantic, the frontend typecheck fails.
//
// Enum and Literal fields are emitted as `string`.
"""

PRIMITIVES = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "null": "null",
}


def discover_read_models() -> list[type[BaseModel]]:
    """Every read Pydantic class defined in `app.models`.

    `*Create` / `*Update` are excluded: those are the write contract, emitted by
    gen_write_models.py.
    """
    found: list[type[BaseModel]] = []
    for info in pkgutil.iter_modules(app.models.__path__):
        if info.name.startswith("_"):
            continue
        module = importlib.import_module(f"app.models.{info.name}")
        for _name, obj in inspect.getmembers(module, inspect.isclass):
            if obj is BaseModel or not issubclass(obj, BaseModel):
                continue
            if obj.__module__ != module.__name__:
                continue
            if obj.__name__.endswith("Create") or obj.__name__.endswith("Update"):
                continue
            found.append(obj)
    found.sort(key=lambda m: m.__name__)
    return found


def ts_type(schema: object, defs: dict[str, dict]) -> str:
    if isinstance(schema, bool):
        return "unknown" if schema else "never"
    if not isinstance(schema, dict):
        return "unknown"
    if "$ref" in schema:
        name = schema["$ref"].rsplit("/", 1)[-1]
        target = defs.get(name)
        if target is not None and "enum" in target:
            return "string"
        return name
    if "anyOf" in schema:
        variants = [ts_type(s, defs) for s in schema["anyOf"]]
        return " | ".join(dict.fromkeys(variants))
    if "enum" in schema and "type" not in schema:
        return "string"
    kind = schema.get("type")
    if kind == "array":
        return f"{ts_type(schema.get('items', {}), defs)}[]"
    if kind == "object":
        additional = schema.get("additionalProperties")
        if additional is not None:
            return f"Record<string, {ts_type(additional, defs)}>"
        props = schema.get("properties", {})
        members = ", ".join(
            f"{key}: {ts_type(value, defs)}" for key, value in sorted(props.items())
        )
        return f"{{ {members} }}"
    if kind in PRIMITIVES:
        return PRIMITIVES[kind]
    return "unknown"


def emit_interface(name: str, schema: dict, defs: dict[str, dict]) -> str:
    required = set(schema.get("required", []))
    properties = schema.get("properties", {})
    lines: list[str] = [f"export interface {name} {{"]
    for field in sorted(properties):
        ftype = ts_type(properties[field], defs)
        mark = "" if field in required else "?"
        lines.append(f"  {field}{mark}: {ftype};")
    lines.append("}")
    return "\n".join(lines)


def render() -> str:
    models = discover_read_models()
    defs: dict[str, dict] = {}
    for model in models:
        defs.update(model.model_json_schema().get("$defs", {}))

    chunks: list[str] = [HEADER]
    for name, def_schema in sorted(defs.items()):
        if def_schema.get("type") != "object":
            continue
        chunks.append(emit_interface(name, def_schema, defs))
        chunks.append("")
    for model in models:
        schema = model.model_json_schema()
        chunks.append(emit_interface(model.__name__, schema, schema.get("$defs", defs)))
        chunks.append("")
    return "\n".join(chunks).rstrip() + "\n"


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render())
    print(f"  wrote {OUT}")


if __name__ == "__main__":
    main()
