#!/usr/bin/env python3
"""Generate the TypeScript write-contract interfaces from the Pydantic models.

Run from backend/:  python gen_write_models.py
Output goes to ../frontend/src/api/generated/writeModels.ts

A sibling of gen_schemas.py rather than an extension of it: that script turns
the *read* models into JSON Schemas for on-disk YAML validation, this one turns
the *write* models (`*Create` / `*Update`) into TypeScript so the client's
create/update calls cannot omit a field the API requires. They share nothing but
the source models and the "regenerate, then gate the diff in CI" discipline.
"""

import importlib
import inspect
import pkgutil
from pathlib import Path

from pydantic import BaseModel

import app.models

OUT = Path(__file__).resolve().parent.parent / "frontend" / "src" / "api" / "generated" / "writeModels.ts"

HEADER = """\
// AUTO-GENERATED — do not edit.
// Generated by backend/gen_write_models.py from the Pydantic write models
// (`*Create` / `*Update` classes in backend/app/models/). Any edits here are
// overwritten the next time the generator runs.
//
// Enum and Literal fields are emitted as `string` to match the hand-written
// entity interfaces in client.ts. The contract this file encodes is the
// required/optional asymmetry: a field the API requires on write is required
// here, and a field the API defaults or accepts as absent is optional.
"""

PRIMITIVES = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "null": "null",
}


def discover_write_models() -> list[type[BaseModel]]:
    """Every `*Create` / `*Update` Pydantic class defined in `app.models`.

    Discovered by walking the package rather than listed by hand, so a model
    added without a generated interface fails the CI gate instead of drifting.
    """
    found: list[type[BaseModel]] = []
    for info in pkgutil.iter_modules(app.models.__path__):
        if info.name.startswith("_"):
            continue
        module = importlib.import_module(f"app.models.{info.name}")
        for _name, obj in inspect.getmembers(module, inspect.isclass):
            if obj is BaseModel or not issubclass(obj, BaseModel):
                continue
            # Restrict to classes *defined* here — risk.py re-exports
            # CommentCreate/DecisionRecord* and would otherwise duplicate them.
            if obj.__module__ != module.__name__:
                continue
            if obj.__name__.endswith("Create") or obj.__name__.endswith("Update"):
                found.append(obj)
    found.sort(key=lambda m: m.__name__)
    return found


def ts_type(schema: object, defs: dict[str, dict]) -> str:
    """Map one JSON Schema node to a TypeScript type string."""
    if isinstance(schema, bool):
        return "unknown" if schema else "never"
    if not isinstance(schema, dict):
        return "unknown"
    if "$ref" in schema:
        name = schema["$ref"].rsplit("/", 1)[-1]
        target = defs.get(name)
        if target is not None and "enum" in target:
            # Enums and Literals are emitted as plain `string` — see HEADER.
            return "string"
        return name
    if "anyOf" in schema:
        variants = [ts_type(s, defs) for s in schema["anyOf"]]
        return " | ".join(dict.fromkeys(variants))
    if "enum" in schema and "type" not in schema:
        return "string"
    kind = schema.get("type")
    if kind == "array":
        item = schema.get("items", {})
        return f"{ts_type(item, defs)}[]"
    if kind == "object":
        additional = schema.get("additionalProperties")
        if additional is not None:
            return f"Record<string, {ts_type(additional, defs)}>"
        props = schema.get("properties", {})
        members = ", ".join(
            f"{key}: {ts_type(value, defs)}"
            for key, value in sorted(props.items())
        )
        return f"{{ {members} }}"
    if kind in PRIMITIVES:
        return PRIMITIVES[kind]
    return "unknown"


def emit_interface(name: str, schema: dict, defs: dict[str, dict]) -> str:
    """Emit `export interface Name { ... }` for an object schema."""
    required = set(schema.get("required", []))
    properties = schema.get("properties", {})
    lines: list[str] = [f"export interface {name} {{"]
    for field in sorted(properties):
        ftype = ts_type(properties[field], defs)
        mark = "" if field in required else "?"
        lines.append(f"  {field}{mark}: {ftype};")
    lines.append("}")
    return "\n".join(lines)


def collect_defs(models: list[type[BaseModel]]) -> dict[str, dict]:
    """All `$defs` reachable from the write models, keyed by name.

    Enums/Literals are kept so `$ref` resolution can inline them as `string`;
    only the object entries are emitted as interfaces.
    """
    collected: dict[str, dict] = {}
    for model in models:
        for name, def_schema in model.model_json_schema().get("$defs", {}).items():
            collected[name] = def_schema
    return collected


def render() -> str:
    """The full contents of the generated file, as a string."""
    models = discover_write_models()
    defs = collect_defs(models)

    chunks: list[str] = [HEADER]

    for name, def_schema in sorted(defs.items()):
        if def_schema.get("type") != "object":
            continue
        chunks.append(emit_interface(name, def_schema, defs))
        chunks.append("")

    creates = [m for m in models if m.__name__.endswith("Create")]
    updates = [m for m in models if m.__name__.endswith("Update")]

    for model in creates:
        schema = model.model_json_schema()
        chunks.append(emit_interface(model.__name__, schema, schema.get("$defs", defs)))
        chunks.append("")

    for model in updates:
        schema = model.model_json_schema()
        chunks.append(emit_interface(model.__name__, schema, schema.get("$defs", defs)))
        chunks.append("")

    return "\n".join(chunks).rstrip() + "\n"


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render())
    print(f"  wrote {OUT}")


if __name__ == "__main__":
    main()
