#!/usr/bin/env python3
"""Generate the frontend's copy of the requirement-lint rule set.

Run from backend/:  .venv/bin/python gen_quality_rules.py

Writes ``frontend/src/lib/qualityRules.json`` from
:mod:`app.services.quality_rules`, so the live editor feedback and the
server-side score check the same things. That file is generated — never
hand-edit it — as with ``schemas/*.json``.

Exits non-zero with ``--check`` if the committed file is out of date, which is
what CI uses to stop the two drifting again.
"""

import json
import sys
from pathlib import Path

from app.services.quality_rules import as_dicts

OUT = Path(__file__).resolve().parent.parent / "frontend" / "src" / "lib" / "qualityRules.json"

BANNER = "GENERATED by backend/gen_quality_rules.py — do not edit"


def payload() -> str:
    return json.dumps(
        {"_comment": BANNER, "rules": as_dicts()},
        indent=2,
        ensure_ascii=False,
    ) + "\n"


def main() -> int:
    want = payload()
    check = "--check" in sys.argv
    have = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    if check:
        if have != want:
            print(f"out of date: {OUT}\nrun: .venv/bin/python gen_quality_rules.py", file=sys.stderr)
            return 1
        print(f"up to date: {OUT}")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(want, encoding="utf-8")
    print(f"wrote {OUT} ({len(as_dicts())} rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
