"""Golden test for the extracted LaTeX risk-register block.

``Publisher.build_latex`` grew too large to hold together, and the risk table
was one of the blocks most prone to escaping bugs. This suite pins the exact
LaTeX the risk section emits *before* the block was extracted into
``_risk_table_latex``, so the extraction is provably behaviour-preserving.

The golden file (``fixtures/risk_table_latex.tex``) was generated by running the
pre-refactor ``build_latex`` over the three risks below and committing the risk
section verbatim.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from app.services.publisher import Publisher
from app.services.yaml_store import YamlStore

FIXTURES = Path(__file__).parent / "fixtures"

# The ten LaTeX metacharacters the escaping rules must neutralise. Kept
# space-separated so each is unambiguous in the golden output.
META = r"& % _ $ \ # { } ~ ^"


def _risks() -> list[dict]:
    """Three risks exercising the whole block: plain, FMECA, and metacharacters
    in every text field."""
    return [
        {
            "id": "RSK-001",
            "title": "Plain risk",
            "severity": "low",
            "probability": "rare",
            "status": "open",
        },
        {
            "id": "RSK-002",
            "title": "FMECA risk",
            "severity": "high",
            "probability": "possible",
            "status": "mitigated",
            "mitigation": "Lubricate and inspect the hinge bearing every 100 flight hours.",
            "failure_mode": "<p>Primary actuator jams</p>",
            "effect": "<p>Control surface freezes mid-flight</p>",
            "cause": "<p>Hinge bearing corrosion</p>",
        },
        {
            "id": "RSK_003",
            "title": f"Meta {META}",
            "severity": f"severity {META}",
            "probability": f"probability {META}",
            "status": f"status {META}",
            "mitigation": f"mitigation {META}",
            "failure_mode": f"<p>failure {META}</p>",
            "effect": f"<p>effect {META}</p>",
            "cause": f"<p>cause {META}</p>",
        },
    ]


@pytest.fixture
def store(tmp_path):
    """A bare project holding exactly the three fixture risks."""
    s = YamlStore(tmp_path / "proj")
    s.ensure_dirs()
    s.write_meta({"name": "Golden"})
    for r in _risks():
        s.create_item("risks", r)
    return s


@pytest.fixture
def pub(store):
    return Publisher(store)


def test_risk_table_latex_matches_golden(pub, store):
    """The extracted block reproduces the pre-refactor output byte-for-byte."""
    risks = store.list_items("risks")
    expected = (FIXTURES / "risk_table_latex.tex").read_text()
    assert "\n".join(pub._risk_table_latex(risks)) + "\n" == expected


def test_risk_table_latex_empty(pub):
    assert pub._risk_table_latex([]) == []


def test_build_latex_contains_method_output_verbatim(pub, store):
    """``build_latex`` extends ``L`` with the method's lines, unchanged."""
    risks = store.list_items("risks")
    block = "\n".join(pub._risk_table_latex(risks))
    latex = pub.build_latex(sections=["risks"])
    assert block in latex


def test_build_latex_summary_has_no_risk_section(pub):
    """Section gating still drops the risk block when it is not requested."""
    latex = pub.build_latex(sections=["summary"])
    assert r"\section{Risk Register}" not in latex
