"""Ensure every API route appears in the generated API reference.

Walks the live FastAPI route table (the same recursive walk used by
test_permissions.py, because a flat scan silently misses every route inside
an ``include_router`` since Starlette 1.x). For every APIRoute whose path
starts with ``/api``, this test asserts the path appears in ``docs/api.md``.

The reference is generated by ``gen_api_reference.py`` from ``app.openapi()``;
this test re-derives the route set *independently* by walking ``app.routes``,
so a bug that made the generator drop routes (rather than merely forget to
regenerate — that is ``test_api_reference_currency.py``'s job) still fails
here. There is no allowlist: the whole point of replacing README's
hand-written tables is that every route is documented, no exceptions.
"""

import re

from fastapi.routing import APIRoute

from app.main import app


class _PrefixedRoute:
    """An APIRoute paired with its fully-qualified path.

    Starlette 1.x stopped flattening ``include_router`` into ``app.routes``:
    an included router now appears as a single wrapper object holding the
    original router plus the prefix it was mounted under, and the routes
    inside it keep their *unprefixed* paths.  This wrapper stores the full
    path so callers don't have to reconstruct it.
    """

    def __init__(self, route, path):
        self._route = route
        self.path = path

    def __getattr__(self, name):
        return getattr(self._route, name)


def _collect_api_routes():
    """Walk the live FastAPI route table and return every APIRoute under /api.

    This is a local copy of the recursion in test_permissions.py so that
    this test stays self-contained — the guarantee that the API reference is
    complete should not depend on a test in another module.
    """
    found: list[_PrefixedRoute] = []

    def walk(routes, prefix: str) -> None:
        for r in routes:
            if isinstance(r, APIRoute):
                found.append(_PrefixedRoute(r, prefix + r.path))
                continue
            # An included sub-router: descend, carrying its mount prefix.
            original = getattr(r, "original_router", None)
            context = getattr(r, "include_context", None)
            if original is not None and hasattr(original, "routes"):
                walk(original.routes, prefix + getattr(context, "prefix", ""))
            elif hasattr(r, "routes"):
                walk(r.routes, prefix + getattr(r, "path", ""))

    walk(app.routes, "")
    return [r for r in found if r.path.startswith("/api")]


def _normalise(path: str) -> str:
    """Collapse every ``{...}`` segment to ``{}`` so the reference's parameter
    names never have to match the route's verbatim."""
    return re.sub(r"\{[^}]+\}", "{}", path)


def test_every_api_route_is_in_the_reference():
    reference_path = __file__.replace(
        "/backend/tests/test_docs_currency.py", "/docs/api.md"
    )
    with open(reference_path, "r") as f:
        reference = f.read()

    reference_normalised = _normalise(reference)
    routes = _collect_api_routes()

    missing: list[str] = []
    for route in routes:
        norm = _normalise(route.path)
        if norm not in reference_normalised:
            missing.append(route.path)

    assert not missing, (
        "API routes missing from docs/api.md: " + ", ".join(sorted(missing))
    )
