"""SysML v2 textual notation export.

SysML v2 uses a human-readable textual syntax (KerML-based) rather than
the XMI-based v1.x. This generates valid .sysml files that can be imported
into tools like the SysML v2 Pilot Implementation.
"""

from __future__ import annotations

from textwrap import indent as text_indent


def export_sysml_v2(store) -> str:
    """Return a SysML v2 textual notation string for the project."""
    meta = store.read_meta()
    reqs = store.list_requirements()
    project_name = meta.get("name", store.root.name)
    safe_name = project_name.replace(" ", "_").replace("-", "_")

    lines: list[str] = []
    lines.append(f"// SysML v2 requirements model generated by reqmesh")
    lines.append(f"// Project: {project_name}")
    lines.append("")
    lines.append(f"package {safe_name} {{")
    lines.append("")

    # --- Part definitions (one per requirement type as a "part") ---
    req_by_parent: dict[str | None, list[dict]] = {}
    for r in reqs:
        pid = r.get("parent") if isinstance(r.get("parent"), str) and r["parent"] else None
        req_by_parent.setdefault(pid, []).append(r)

    # Render requirements as SysML requirement definitions.
    def render_req(r: dict, indent_level: int = 2) -> list[str]:
        rid = r["id"].replace("-", "_").replace(".", "_")
        body: list[str] = []
        prefix = "  " * indent_level

        name = r.get("name", rid) or rid
        # Escape quotes in name
        name_escaped = name.replace('"', '\\"')
        body.append(f"{prefix}requirement def {rid} {{")
        body.append(f"{prefix}  doc /* {name_escaped} */")
        body.append(f"{prefix}  :>> status = {r.get('status', 'proposed')};")
        body.append(f"{prefix}  :>> priority = {r.get('priority', 'medium')};")
        body.append(f"{prefix}  :>> verificationMethod = {r.get('verification_method', 'test')};")

        desc = r.get("description", "").replace("<p>", "").replace("</p>", "").replace("<br>", "\n")
        if desc.strip():
            desc_escaped = desc.replace('"', '\\"').replace("\n", "\\n")
            body.append(f"{prefix}  text /* \"{desc_escaped[:500]}\" */")
        if r.get("rationale"):
            rat_escaped = r["rationale"].replace('"', '\\"')
            body.append(f"{prefix}  :>> rationale = \"{rat_escaped[:500]}\";")
        if r.get("source"):
            src_escaped = r["source"].replace('"', '\\"')
            body.append(f"{prefix}  :>> source = \"{src_escaped[:300]}\";")

        # Relations
        for rel in r.get("relations") or []:
            tgt = rel["target"].replace("-", "_").replace(".", "_")
            rel_type = rel["type"]
            if rel_type in ("refines",):
                body.append(f"{prefix}  refine requirement {tgt};")
            elif rel_type in ("satisfies", "verified_by"):
                body.append(f"{prefix}  satisfy requirement {tgt};")
            elif rel_type == "derives":
                body.append(f"{prefix}  derive requirement {tgt};")

        # Verification cases
        for vc_id in r.get("verification_cases") or []:
            vc_safe = vc_id.replace("-", "_").replace(".", "_")
            body.append(f"{prefix}  verify requirement {vc_safe};")

        # Children
        children = req_by_parent.get(r["id"], [])
        for child in children:
            body.extend(render_req(child, indent_level + 1))

        body.append(f"{prefix}}}")
        if indent_level == 2:
            body.append("")
        return body

    top_level = req_by_parent.get(None, [])
    for r in top_level:
        lines.extend(render_req(r))

    # Verification cases as separate defs
    vcs = store.list_verification_cases()
    if vcs:
        lines.append("")
        lines.append("  // Verification Cases")
        for vc in vcs:
            vcid = vc["id"].replace("-", "_").replace(".", "_")
            lines.append(f"  requirement def {vcid} {{")
            lines.append(f"    doc /* {vc.get('name', vcid)} */")
            lines.append(f"    :>> status = {vc.get('status', 'pending')};")
            lines.append(f"    :>> method = {vc.get('method', 'test')};")
            for req_id in vc.get("verified_requirements", []):
                rid_safe = req_id.replace("-", "_").replace(".", "_")
                lines.append(f"    verify requirement {rid_safe};")
            lines.append(f"  }}")
            lines.append("")

    lines.append("}")
    return "\n".join(lines)
